version: "2"

services:

  db:
    build: db
    image: steedos/mattermost-docker_db:1.0
    # read_only: true
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /srv/mattermost/volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    image: steedos/mattermost-docker_app:1.0
    restart: unless-stopped
    volumes:
      - /srv/mattermost/volumes/app/mattermost/config:/mattermost/config:rw
      - /srv/mattermost/volumes/app/mattermost/data:/mattermost/data:rw
      - /srv/mattermost/volumes/app/mattermost/logs:/mattermost/logs:rw
      - /srv/mattermost/volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - /srv/mattermost/volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # - DB_HOST=192.168.1.150
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    image: steedos/mattermost-docker_web:1.0
    ports:
      - "80:80"
      - "443:443"
    # read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - /etc/letsencrypt/archive/messenger.steedos.cn:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    environment:
     - MATTERMOST_ENABLE_SSL=true
